### ISSUE TITLE
add dev version mods in gradle settings

### ISSUE THREAD

**Issue by Bogdan-G** [ganymedes01/Et-Futurum#62]
add versions of mod dependencies, such as the CCC/NEI:
`\Et-Futurum\build\sources\java\ganymedes01\etfuturum\client\nei\BannerPatternHandler.java:8: error: package codechicken.nei does not exist
import codechicken.nei.PositionedStack;`

I'm build in gradle 2.0 console (msysgit), project through the cloned `git clone` for https.

**Comment by buttilda** [comment]
All you have to do is create a libs folder and place the dev versions of those jars inside of it

**Comment by buttilda** [comment]
Also, I often commit unfinished or broken pieces of code to the repo. I don't recommend using any of it. So don't blame me if I destroy your world XD

**Comment by Bogdan-G** [comment]
@ganymedes01  I have ordered the settings gradle upload them))
I checked, no, world works.
